// The built-in effects library. Each entry is a template (see template.ts) plus the description the
// planner reads when it decides which effects an edit needs, so describe when an editor reaches for it.
// Every entry is rendered by scripts/effects-test.ts: keep it passing when adding one.
import type { ParamSpec } from "./template";
import type { EffectDef } from "./types";

const num = (min: number, max: number, def: number, doc?: string): ParamSpec => ({ type: "number", min, max, default: def, ...(doc ? { doc } : {}) });
const color = (def: string, doc?: string): ParamSpec => ({ type: "color", default: def, ...(doc ? { doc } : {}) });
const text = (doc: string, max = 60): ParamSpec => ({ type: "text", max, doc });
const oneOf = (values: string[], def: string, doc?: string): ParamSpec => ({ type: "enum", values, default: def, ...(doc ? { doc } : {}) });
const gain = (def = 0.7) => num(0, 2, def, "loudness next to the voice (1 = as loud)");

/** zoompan on a 2× upscale, so the moving crop stays sharp. */
const zoompan = (z: string, x = "iw/2-(iw/zoom/2)", y = "ih/2-(ih/zoom/2)") =>
  `scale={{=W*2}}:{{=H*2}},zoompan=z='${z}':x='${x}':y='${y}':d=1:s={{W}}x{{H}}:fps={{fps}}`;

export const GRADES: Record<string, string> = {
  punchy: "eq=contrast=1.08:saturation=1.18:brightness=0.01",
  warm: "colorbalance=rs=0.05:gs=0.01:bs=-0.06:rm=0.04:bm=-0.05:rh=0.03:bh=-0.03,eq=contrast=1.05:saturation=1.1:gamma=1.02",
  cold: "colorbalance=rs=-0.05:bs=0.07:rm=-0.03:bm=0.05:rh=-0.02:bh=0.04,eq=saturation=0.95:contrast=1.05",
  cinematic: "colorbalance=rs=-0.06:bs=0.07:rh=0.07:gh=0.02:bh=-0.07,eq=contrast=1.1:saturation=1.05",
  vintage: "curves=all='0/0.07 0.5/0.5 1/0.94',eq=saturation=0.78:gamma=1.02,colorbalance=rs=0.04:gs=0.015:bs=-0.04:rm=0.03:bm=-0.03",
  noir: "hue=s=0,eq=contrast=1.35:brightness=-0.03,curves=all='0/0 0.25/0.15 0.75/0.85 1/1'",
  sad: "eq=saturation=0.55:contrast=0.95:gamma=1.04,colorbalance=bs=0.08:bm=0.05:rh=-0.02,curves=all='0/0.06 1/0.95'",
  neon: "eq=saturation=1.6:contrast=1.15,vibrance=intensity=0.4,colorbalance=bs=0.08:rh=0.06",
  bleach: "eq=saturation=0.45:contrast=1.3,curves=all='0/0 0.5/0.55 1/1'",
  sunset: "colorbalance=rs=0.08:gs=-0.02:bs=0.03:rm=0.06:bm=-0.02:rh=0.05:bh=-0.05,eq=saturation=1.15",
};

// ── on one part of the source (camera moves and looks) ───────────────

const SEGMENT: EffectDef[] = [
  { name: "slow_push", kind: "segment", timing: "whole", cropOnly: true, tags: ["camera", "emotional", "build"],
    description: "Slowly pushes in over the part: draws the viewer into an emotional or serious moment.",
    params: { amount: num(0.03, 0.3, 0.1, "how far it zooms in by the end (0.1 = 10%)") },
    filter: zoompan("min(1+{{amount}}*on/{{frames}},1+{{amount}})") },
  { name: "punch_in", kind: "segment", timing: "whole", cropOnly: true, tags: ["camera", "jump cut", "comedy"],
    description: "A tighter framing for the whole part: a jump-cut punch-in when a line lands.",
    params: { amount: num(0.05, 0.35, 0.12, "how much tighter (0.12 = 12%)") },
    filter: "scale={{=even(W*(1+amount))}}:{{=even(H*(1+amount))}},crop={{W}}:{{H}}" },
  { name: "zoom_out", kind: "segment", timing: "whole", cropOnly: true, tags: ["camera", "ending", "reveal"],
    description: "Starts tight and pulls back: the final beat, a reveal, or letting a moment go.",
    params: { amount: num(0.05, 0.35, 0.14) },
    filter: zoompan("max(1+{{amount}}-{{amount}}*on/{{frames}},1.0)") },
  { name: "ken_burns", kind: "segment", timing: "whole", cropOnly: true, tags: ["camera", "photo", "documentary"],
    description: "Slow zoom with a sideways pan: photos, archive images and still-looking shots.",
    params: { amount: num(0.05, 0.3, 0.14) },
    filter: zoompan("1.04+{{amount}}*on/{{frames}}", "(iw-iw/zoom)*(0.2+0.6*on/{{frames}})", "(ih-ih/zoom)/2") },
  { name: "drift", kind: "segment", timing: "whole", cropOnly: true, tags: ["camera", "wide", "calm"],
    description: "A gentle sideways drift: wide shots of several people or a stage.",
    filter: zoompan("1.08", "(iw-iw/zoom)*(0.35+0.3*on/{{frames}})", "(ih-ih/zoom)/2") },
  { name: "bw", kind: "segment", timing: "whole", tags: ["look", "flashback", "memory", "sad"],
    description: "Black and white for this part: a flashback, a memory, a serious aside.",
    filter: "hue=s=0,eq=contrast=1.1" },
  { name: "sepia", kind: "segment", timing: "whole", tags: ["look", "flashback", "vintage"],
    description: "Warm sepia for this part: old times, nostalgia, a flashback.",
    filter: "colorchannelmixer=.393:.769:.189:0:.349:.686:.168:0:.272:.534:.131" },
  { name: "mirror", kind: "segment", timing: "whole", tags: ["look", "variety"],
    description: "Flips the part left to right (hides a repeated shot; never on shots with readable text).",
    filter: "hflip" },
];

// ── on the edited clip, over a time range ─────────────────────────────

const VIDEO: EffectDef[] = [
  { name: "zoom_punch", kind: "video", timing: "instant", duration: 0.45, tags: ["camera", "impact", "hype", "anime", "beat"],
    description: "A fast zoom hit that settles back: punchlines, beats, impacts, a name or number landing.",
    params: { amount: num(0.05, 0.5, 0.18, "how far it jumps in"), decay: num(2, 20, 8, "how fast it settles") },
    filter: zoompan("1+{{amount}}*exp(-on/{{fps}}*{{decay}})") },
  { name: "zoom_in", kind: "video", timing: "range", tags: ["camera", "build", "tension"],
    description: "A smooth zoom in across the range: tension builds, a reveal is coming.",
    params: { amount: num(0.05, 0.5, 0.15) },
    filter: zoompan("1+{{amount}}*on/{{frames}}") },
  { name: "pull_back", kind: "video", timing: "range", tags: ["camera", "ending", "memory", "release"],
    description: "Starts tighter and slowly pulls back across the range: a moment ending, fading into memory, letting go.",
    params: { amount: num(0.05, 0.5, 0.15) },
    filter: zoompan("max(1+{{amount}}-{{amount}}*on/{{frames}},1)") },
  { name: "zoom_to", kind: "video", timing: "range", tags: ["camera", "info", "focus", "reveal"],
    description: "Zooms toward one spot on screen (fx, fy from 0 to 1) and holds: look at this face, object or detail.",
    params: { fx: num(0, 1, 0.5, "horizontal position"), fy: num(0, 1, 0.4, "vertical position"), amount: num(1.2, 3, 1.8, "final zoom") },
    filter: zoompan("min(1+({{amount}}-1)*on/({{fps}}*0.35),{{amount}})", "max(0,min(iw-iw/zoom,iw*{{fx}}-iw/zoom/2))", "max(0,min(ih-ih/zoom,ih*{{fy}}-ih/zoom/2))") },
  { name: "zoom_pulse", kind: "video", timing: "range", tags: ["camera", "beat", "hype", "anime", "music"],
    description: "Rhythmic zoom pulses, like a heartbeat or a beat drop.",
    params: { amount: num(0.02, 0.2, 0.06), rate: num(0.5, 6, 2, "pulses per second") },
    filter: zoompan("1+{{amount}}*pow(abs(sin(PI*on/{{fps}}*{{rate}})),6)") },
  { name: "shake", kind: "video", timing: "range", duration: 0.5, tags: ["camera", "impact", "hype", "anime", "shock"],
    description: "Camera shake: an impact, a shock, an explosion of laughter, anime hits. decay > 0 makes it die down.",
    params: { intensity: num(0.1, 1, 0.7), speed: num(1, 10, 5, "how fast it shakes"), decay: num(0, 10, 0, "0 = steady, higher = dies down") },
    filter: "scale={{=even(W*(1+0.1*intensity))}}:{{=even(H*(1+0.1*intensity))}},crop={{W}}:{{H}}:x='(in_w-out_w)/2*(1+{{intensity}}*exp(-{{decay}}*t)*(sin(t*{{speed}}*6.1)+0.6*sin(t*{{speed}}*13.7))/1.6)':y='(in_h-out_h)/2*(1+{{intensity}}*exp(-{{decay}}*t)*(sin(t*{{speed}}*7.3+1)+0.5*sin(t*{{speed}}*11.9))/1.5)'" },
  { name: "spin", kind: "video", timing: "instant", duration: 0.5, tags: ["camera", "transition", "hype", "anime"],
    description: "The frame spins around: a playful or hype move, often into a cut.",
    params: { turns: num(0.25, 2, 1) },
    filter: "scale={{=even(W*1.25)}}:{{=even(H*1.25)}},rotate='{{turns}}*2*PI*t/{{dur}}':fillcolor=black,crop={{W}}:{{H}}" },
  { name: "wobble", kind: "video", timing: "range", tags: ["camera", "dizzy", "comedy", "drunk"],
    description: "A slow rocking tilt: dizziness, confusion, a comic 'what just happened'.",
    params: { degrees: num(1, 10, 3), speed: num(1, 10, 3) },
    filter: "scale={{=even(W*1.14)}}:{{=even(H*1.14)}},rotate='{{degrees}}*PI/180*sin(t*{{speed}})':fillcolor=black,crop={{W}}:{{H}}" },
  { name: "strobe", kind: "video", timing: "range", tags: ["flash", "hype", "beat", "music"],
    description: "Flickering brightness: hype drops, chaos, music peaks.",
    params: { amount: num(0.1, 0.8, 0.35), period: num(0.05, 1, 0.12, "seconds per flicker") },
    filter: "eq=brightness='{{amount}}*lt(mod(t,{{period}}),{{period}}/2)':eval=frame" },
  { name: "rgb_split", kind: "video", timing: "range", tags: ["glitch", "hype", "anime", "tension"],
    description: "Red and blue channels pulled apart: glitchy tension, impact frames, edgy energy.",
    params: { px: num(2, 40, 10, "how far apart, in pixels") },
    filter: "rgbashift=rh={{=round(px)}}:bh=-{{=round(px)}}:edge=smear" },
  { name: "glitch", kind: "video", timing: "range", duration: 0.4, tags: ["glitch", "transition", "hype", "tech", "horror"],
    description: "Digital glitch: split colours, noise and hue flicker. Tech topics, twists, jump scares, hype cuts.",
    params: { px: num(4, 40, 14), noise: num(5, 60, 25), hue: num(20, 180, 90) },
    filter: "rgbashift=rh={{=round(px)}}:gh=-{{=round(px/2)}}:bh=-{{=round(px/3)}}:edge=smear,noise=alls={{=round(noise)}}:allf=t,hue=h='{{hue}}*sin(t*37)*lt(mod(t,0.24),0.12)'" },
  { name: "vhs", kind: "video", timing: "range", tags: ["retro", "nostalgia", "look", "lofi"],
    description: "VHS tape look: colour bleed, noise, soft focus and scanlines. Nostalgia, old footage, lo-fi.",
    params: { noise: num(0, 40, 12) },
    filter: "chromashift=cbh=4:crh=-4:edge=smear,eq=saturation=1.25:contrast=1.05,noise=alls={{=round(noise)}}:allf=t,gblur=sigma=0.6,drawgrid=w=iw:h=4:t=1:c=black@0.25" },
  { name: "film", kind: "video", timing: "range", tags: ["retro", "nostalgia", "look", "cinematic"],
    description: "Old film: grain, flicker, faded blacks and a vignette. Memories, old times, cinematic moods.",
    params: { grain: num(0, 40, 14) },
    filter: "noise=alls={{=round(grain)}}:allf=t,eq=brightness='0.015*sin(t*23)':eval=frame,curves=all='0/0.05 1/0.95',vignette=PI/5" },
  { name: "glow", kind: "video", timing: "range", tags: ["look", "dreamy", "anime", "romantic", "highlight"],
    description: "A soft bloom on the highlights: dreamy, romantic, glamorous, anime shine.",
    params: { radius: num(5, 60, 26), amount: num(0.1, 0.7, 0.3) },
    filter: "[in]split[_a][_b];[_b]gblur=sigma={{radius}}[_g];[_a][_g]blend=c0_mode=screen:c0_opacity={{amount}}[out]" },
  { name: "dreamy", kind: "video", timing: "range", tags: ["look", "dreamy", "memory", "romantic"],
    description: "Soft, hazy and bright: a daydream, a fond memory, a romantic beat.",
    params: { amount: num(0.2, 0.9, 0.55) },
    filter: "[in]split[_a][_b];[_b]gblur=sigma=40,eq=brightness=0.05:saturation=1.1[_g];[_a][_g]blend=c0_mode=softlight:c0_opacity={{amount}}[out]" },
  { name: "edge_glow", kind: "video", timing: "range", tags: ["anime", "hype", "neon", "stylised"],
    description: "Glowing white outlines traced over the picture: anime power-ups, neon, stylised hype.",
    params: { amount: num(0.2, 1, 0.6) },
    // Edges of the brightness only (chroma set neutral), so the split keeps its colour format.
    filter: "[in]split[_a][_b];[_b]edgedetect=low=0.08:high=0.25,lutyuv=u=128:v=128,gblur=sigma=1.5[_e];[_a][_e]blend=c0_mode=screen:c0_opacity={{amount}}[out]" },
  { name: "blur_dip", kind: "video", timing: "instant", duration: 0.8, tags: ["transition", "memory", "dreamy"],
    description: "The picture blurs out and back in, peaking in the middle: into or out of a memory, time passing.",
    params: { amount: num(4, 40, 18) },
    filter: "[in]split[_a][_b];[_b]gblur=sigma={{amount}}[_g];[_a][_g]blend=all_expr='A+(B-A)*clip(1-abs(T-{{=dur/2}})/{{=dur/2}},0,1)'[out]" },
  { name: "motion_blur", kind: "video", timing: "range", tags: ["speed", "action", "anime", "smooth"],
    description: "Blends frames into motion blur: fast action, speed ramps, whip movement.",
    params: { frames: num(2, 8, 4) },
    filter: "tmix=frames={{=round(frames)}}" },
  { name: "trails", kind: "video", timing: "range", tags: ["dreamy", "trippy", "music", "anime"],
    description: "Ghost trails behind moving things: trippy, dreamy, music moments.",
    params: { decay: num(0.8, 0.99, 0.93) },
    filter: "format=gbrp,lagfun=decay={{decay}},format=yuv420p" },
  { name: "blur", kind: "video", timing: "range", tags: ["focus", "censor", "background"],
    description: "Blurs the picture: out-of-focus moments, behind text, hiding something.",
    params: { amount: num(2, 40, 12) },
    filter: "gblur=sigma={{amount}}" },
  { name: "zoom_blur", kind: "video", timing: "instant", duration: 0.3, tags: ["impact", "speed", "anime", "transition"],
    description: "A zoom smear: impact frames and fast pushes in anime or action edits.",
    filter: "[in]split[_a][_b];[_b]scale={{=even(W*1.15)}}:{{=even(H*1.15)}},crop={{W}}:{{H}},gblur=sigma=8[_z];[_a][_z]blend=all_mode=average[out]" },
  { name: "pixelate", kind: "video", timing: "range", tags: ["glitch", "censor", "retro", "game"],
    description: "Chunky pixels: censoring, retro games, a digital transition.",
    params: { size: num(4, 60, 16, "pixel size") },
    filter: "scale={{=even(W/size)}}:{{=even(H/size)}}:flags=neighbor,scale={{W}}:{{H}}:flags=neighbor" },
  { name: "anime_pop", kind: "video", timing: "range", tags: ["anime", "look", "vivid", "hype"],
    description: "Anime-style pop: sharper lines, vivid colours, more contrast.",
    params: { saturation: num(1, 2, 1.35), contrast: num(1, 1.4, 1.12), sharpen: num(0, 2, 1) },
    filter: "unsharp=5:5:{{sharpen}}:5:5:0,eq=saturation={{saturation}}:contrast={{contrast}},vibrance=intensity=0.25" },
  { name: "grade", kind: "video", timing: "range", tags: ["look", "colour"],
    description: `A colour grade: ${Object.keys(GRADES).join(", ")}. sad = cold and desaturated, noir = hard black and white, neon = vivid night colours.`,
    params: { style: oneOf(Object.keys(GRADES), "punchy") },
    variants: { param: "style", filters: GRADES } },
  { name: "black_white", kind: "video", timing: "range", tags: ["look", "sad", "flashback", "drama"],
    description: "Black and white over a time range of the clip: drama, a sad turn, a memory.",
    filter: "hue=s=0,eq=contrast=1.12" },
  { name: "sepia_tone", kind: "video", timing: "range", tags: ["look", "vintage", "memory"],
    description: "Sepia over a time range of the clip.",
    filter: "colorchannelmixer=.393:.769:.189:0:.349:.686:.168:0:.272:.534:.131" },
  { name: "invert", kind: "video", timing: "instant", duration: 0.12, tags: ["impact", "anime", "flash", "shock"],
    description: "Inverted colours for a split second: anime impact frames, shocks.",
    filter: "negate" },
  { name: "rainbow", kind: "video", timing: "range", tags: ["trippy", "party", "comedy"],
    description: "Colours cycle through the rainbow: trippy, party, absurd comedy.",
    params: { speed: num(0.5, 6, 2, "cycles per second") },
    filter: "hue=h='t*{{speed}}*360'" },
  { name: "thermal", kind: "video", timing: "range", tags: ["stylised", "tech", "night"],
    description: "Heat-map colours: tech, surveillance, a stylised aside.",
    filter: "pseudocolor=p=inferno" },
  { name: "vignette", kind: "video", timing: "range", tags: ["look", "focus", "cinematic", "sad"],
    description: "Darkened corners that pull the eye to the middle.",
    params: { strength: num(0.2, 1.2, 0.6) },
    filter: "vignette=angle={{strength}}" },
  { name: "letterbox", kind: "video", timing: "range", tags: ["cinematic", "drama"],
    description: "Black cinema bars top and bottom: dramatic, cinematic moments.",
    params: { bar: num(0.03, 0.2, 0.08, "bar height as a share of the frame") },
    filter: "drawbox=x=0:y=0:w=iw:h=ih*{{bar}}:color=black:t=fill,drawbox=x=0:y=ih*(1-{{bar}}):w=iw:h=ih*{{bar}}:color=black:t=fill" },
  { name: "border", kind: "video", timing: "range", tags: ["frame", "highlight", "anime", "info"],
    description: "A solid coloured frame around the picture.",
    params: { color: color("#FFFFFF"), thickness: num(4, 80, 18), opacity: num(0.2, 1, 1) },
    filter: "drawbox=x=0:y=0:w=iw:h=ih:color={{color:ff}}@{{opacity}}:t={{=round(thickness)}}" },
  { name: "border_blink", kind: "video", timing: "range", tags: ["frame", "alert", "hype", "beat"],
    description: "A frame that blinks on and off: alerts, warnings, beat-synced hype.",
    params: { color: color("#FF3B30"), thickness: num(4, 80, 20), period: num(0.1, 2, 0.4) },
    filter: "drawbox=x=0:y=0:w=iw:h=ih:color={{color:ff}}:t={{=round(thickness)}}:enable='lt(mod(t,{{period}}),{{period}}*0.55)'" },
  { name: "lut", kind: "video", timing: "range", tags: ["look", "colour", "custom"],
    description: "Applies a colour LUT from assets/luts (.cube): your own grade.",
    params: { file: { type: "asset", kinds: ["lut"] } },
    filter: "lut3d=file='{{file:path}}'" },
];

// ── generated pictures laid over the clip ─────────────────────────────

const GRAPHIC: EffectDef[] = [
  { name: "flash", kind: "graphic", timing: "instant", duration: 0.25, tags: ["flash", "impact", "transition", "beat", "anime"],
    description: "A flash of colour that fades out: cuts, impacts, camera-flash moments, beats. White by default.",
    params: { color: color("#FFFFFF"), opacity: num(0.2, 1, 0.9) },
    graphic: "color=c={{color:ff}}:s={{W}}x{{H}}:d={{dur}}:r={{fps}},format=rgba,colorchannelmixer=aa={{opacity}},fade=t=out:st=0:d={{dur}}:alpha=1" },
  { name: "dip", kind: "graphic", timing: "instant", duration: 0.7, tags: ["transition", "sad", "time", "mood"],
    description: "Fades to a colour and back: time passing, a change of mood, a sad pause. Black by default.",
    params: { color: color("#000000"), opacity: num(0.3, 1, 1) },
    graphic: "color=c={{color:ff}}:s={{W}}x{{H}}:d={{dur}}:r={{fps}},format=rgba,colorchannelmixer=aa={{opacity}},fade=t=in:st=0:d={{=dur/2}}:alpha=1,fade=t=out:st={{=dur/2}}:d={{=dur/2}}:alpha=1" },
  { name: "border_glow", kind: "graphic", timing: "range", static: true, tags: ["frame", "neon", "anime", "highlight", "hype"],
    description: "A soft glowing frame around the edges: anime edits, highlights, neon hype.",
    params: { color: color("#32D2FF"), thickness: num(6, 60, 22), softness: num(4, 40, 16) },
    graphic: "color=c=black@0.0:s={{W}}x{{H}}:d={{dur}}:r={{fps}},format=rgba,drawbox=x=0:y=0:w=iw:h=ih:color={{color:ff}}@1:t={{=round(thickness)}}:replace=1,gblur=sigma={{softness}}" },
  { name: "neon_border", kind: "graphic", timing: "range", static: true, tags: ["frame", "neon", "anime", "hype", "night"],
    description: "A neon tube frame: a bright core line inside a coloured glow.",
    params: { color: color("#FF2D95"), thickness: num(6, 40, 16) },
    graphic: "color=c=black@0.0:s={{W}}x{{H}}:d={{dur}}:r={{fps}},format=rgba,drawbox=x=10:y=10:w=iw-20:h=ih-20:color={{color:ff}}@1:t={{=round(thickness*1.6)}}:replace=1,gblur=sigma=16,drawbox=x={{=round(10+thickness*0.4)}}:y={{=round(10+thickness*0.4)}}:w=iw-{{=round(20+thickness*0.8)}}:h=ih-{{=round(20+thickness*0.8)}}:color={{color:ff}}@1:t={{=round(max(4,thickness/2))}}:replace=1,drawbox=x={{=round(10+thickness*0.4+max(4,thickness/2)/2-1)}}:y={{=round(10+thickness*0.4+max(4,thickness/2)/2-1)}}:w=iw-{{=round(20+thickness*0.8+max(4,thickness/2)-2)}}:h=ih-{{=round(20+thickness*0.8+max(4,thickness/2)-2)}}:color=white@0.95:t=2:replace=1" },
  { name: "speed_lines", kind: "graphic", timing: "range", static: true, tags: ["anime", "hype", "impact", "speed", "shock"],
    description: "Anime speed lines rushing in from the edges toward the centre: shock, intensity, a dramatic realisation.",
    params: { color: color("#FFFFFF"), density: num(20, 90, 48, "how many lines"), clear: num(0.15, 0.6, 0.34, "size of the clear centre") },
    graphic: "color=c=black@0.0:s={{W}}x{{H}}:d={{dur}}:r={{fps}},format=rgba,geq=r='{{color:r}}':g='{{color:g}}':b='{{color:b}}':a='255*gt(abs(sin(atan2(Y-H/2,X-W/2)*{{=round(density)}}+sin(atan2(Y-H/2,X-W/2)*7)*2)),0.985)*gt(hypot((X-W/2)/W,(Y-H/2)/H),{{clear}}/2)*min(1,(hypot((X-W/2)/W,(Y-H/2)/H)-{{clear}}/2)*6)'" },
  { name: "light_leak", kind: "graphic", timing: "range", tags: ["dreamy", "warm", "nostalgia", "transition", "romantic"],
    description: "A warm drifting light leak washing over the picture: dreamy, nostalgic, romantic transitions.",
    params: { color: color("#FF9F43"), opacity: num(0.1, 0.7, 0.35), speed: num(0.005, 0.1, 0.02) },
    graphic: "gradients=s={{W}}x{{H}}:c0={{color:ff}}:c1=black@0:x0={{=round(W*0.15)}}:y0=0:x1={{W}}:y1={{H}}:speed={{speed}}:d={{dur}}:r={{fps}}:type=radial,format=rgba,colorchannelmixer=aa={{opacity}}" },
  { name: "progress_bar", kind: "graphic", timing: "range", tags: ["info", "retention", "tutorial"],
    description: "A bar that fills across the screen as the clip plays: keeps viewers watching informational clips.",
    params: { color: color("#FFC83D"), height: num(4, 40, 12), position: oneOf(["bottom", "top"], "bottom") },
    graphic: "color=c={{color:ff}}:s={{W}}x{{=round(height)}}:d={{dur}}:r={{fps}},format=rgba",
    x: "-w+w*t/{{dur}}", y: "{{position}}" },
];

// ── text and vector shapes (ASS) ───────────────────────────────────────
// Styles (Big, Banner, Callout, Shape) are defined in compile.ts. {{text:ass}} escapes and handles RTL.

const TEXT: EffectDef[] = [
  { name: "big_text", kind: "text", timing: "instant", duration: 1.2, tags: ["impact", "hype", "comedy", "info", "anime"],
    description: "Big impact text that pops in: a punchline word, 'WAIT…', a number, a reaction.",
    params: { text: text("the words to show", 40), color: color("#FFFFFF"), outline: color("#000000"), size: num(50, 220, 120), y: num(0.1, 0.9, 0.42, "height on screen, 0 = top") },
    ass: ["Dialogue: 6,{{from:time}},{{to:time}},Big,,0,0,0,,{\\an5\\pos({{=W/2}},{{=H*y}})\\fs{{=round(size)}}\\1c{{color:acolor}}\\3c{{outline:acolor}}\\fad(60,160)\\fscx45\\fscy45\\t(0,140,\\fscx112\\fscy112)\\t(140,240,\\fscx100\\fscy100)}{{text:ass}}"] },
  { name: "type_on", kind: "text", timing: "range", tags: ["info", "tech", "suspense", "quote"],
    description: "Text that types itself on, letter by letter (keep it short): a quote, a date, a caption for what we see.",
    params: { text: text("the words to type", 50), color: color("#FFFFFF"), y: num(0.1, 0.9, 0.3) },
    ass: ["Dialogue: 6,{{from:time}},{{to:time}},Callout,,0,0,0,,{\\an5\\pos({{=W/2}},{{=H*y}})\\1c{{color:acolor}}\\3c&H00000000&\\bord3\\shad0\\fad(0,200)\\clip({{=rtl*W}},0,{{=rtl*W}},{{H}})\\t(0,{{=round(min(dur*600,1800))}},\\clip(0,0,{{W}},{{H}}))}{{text:ass}}"] },
  { name: "banner", kind: "text", timing: "range", tags: ["info", "title", "topic", "news"],
    description: "Text on a solid band near the top: the topic, a question, 'PART 2', a news-style strap.",
    params: { text: text("the banner text"), color: color("#FFFFFF"), box: color("#E3342F"), y: num(0.04, 0.5, 0.2, "height on screen, 0 = top (the hook card sits near the top at first)") },
    ass: ["Dialogue: 5,{{from:time}},{{to:time}},Banner,,0,0,0,,{\\an8\\pos({{=W/2}},{{=H*y}})\\1c{{color:acolor}}\\3c{{box:acolor}}\\fad(140,140)}{{text:ass}}"] },
  { name: "lower_third", kind: "text", timing: "range", tags: ["info", "name", "documentary", "news"],
    description: "A name or label that slides in low on the left: who's speaking, a place, a date, a source.",
    params: { text: text("the label", 40), color: color("#FFFFFF"), box: color("#111111"), y: num(0.3, 0.92, 0.64, "height on screen, 0 = top; captions sit around 0.72-0.8") },
    ass: ["Dialogue: 5,{{from:time}},{{to:time}},Banner,,0,0,0,,{\\an1\\move(-700,{{=round(H*y)}},60,{{=round(H*y)}},0,260)\\1c{{color:acolor}}\\3c{{box:acolor}}\\fad(0,200)}{{text:ass}}"] },
  { name: "callout", kind: "text", timing: "range", tags: ["info", "comedy", "explain", "highlight"],
    description: "A small text bubble that pops up at a spot on screen: point something out, add context, a joke aside.",
    params: { text: text("the note", 40), x: num(0.1, 0.9, 0.5), y: num(0.1, 0.9, 0.3), color: color("#111111"), box: color("#FFFFFF") },
    ass: ["Dialogue: 6,{{from:time}},{{to:time}},Callout,,0,0,0,,{\\an5\\pos({{=round(W*x)}},{{=round(H*y)}})\\1c{{color:acolor}}\\3c{{box:acolor}}\\fad(80,120)\\fscx50\\fscy50\\t(0,160,\\fscx106\\fscy106)\\t(160,240,\\fscx100\\fscy100)}{{text:ass}}"] },
  { name: "arrow", kind: "text", timing: "range", tags: ["info", "highlight", "comedy", "explain"],
    description: "A bold arrow whose tip points at a spot (x,y from 0 to 1): look here. angle 0 points right, 90 up, -90 down, 180 left.",
    params: { x: num(0.05, 0.95, 0.5), y: num(0.05, 0.95, 0.5), angle: num(-180, 180, -90), color: color("#FF3B30") },
    ass: ["Dialogue: 7,{{from:time}},{{to:time}},Shape,,0,0,0,,{\\an7\\pos({{=round(W*x-170)}},{{=round(H*y-45)}})\\org({{=round(W*x)}},{{=round(H*y)}})\\frz{{angle}}\\1c{{color:acolor}}\\3c&H00000000&\\bord5\\fad(80,120)\\p1}m 0 27 l 110 27 l 110 0 l 170 45 l 110 90 l 110 63 l 0 63{\\p0}"] },
  { name: "circle", kind: "text", timing: "range", tags: ["info", "highlight", "explain"],
    description: "A ring drawn around a spot (centre x,y from 0 to 1): circle a face, an object, a detail.",
    params: { x: num(0.05, 0.95, 0.5), y: num(0.05, 0.95, 0.4), radius: num(0.03, 0.4, 0.12, "as a share of the width"), color: color("#FF3B30"), thickness: num(3, 30, 10) },
    ass: ["Dialogue: 7,{{from:time}},{{to:time}},Shape,,0,0,0,,{\\an5\\pos({{=round(W*x)}},{{=round(H*y)}})\\1a&HFF&\\3c{{color:acolor}}\\bord{{=round(thickness)}}\\shad0\\fad(60,140)\\p1}m {{=round(W*radius)}} 0 b {{=round(W*radius)}} {{=round(W*radius*0.5523)}} {{=round(W*radius*0.5523)}} {{=round(W*radius)}} 0 {{=round(W*radius)}} b {{=round(-W*radius*0.5523)}} {{=round(W*radius)}} {{=round(-W*radius)}} {{=round(W*radius*0.5523)}} {{=round(-W*radius)}} 0 b {{=round(-W*radius)}} {{=round(-W*radius*0.5523)}} {{=round(-W*radius*0.5523)}} {{=round(-W*radius)}} 0 {{=round(-W*radius)}} b {{=round(W*radius*0.5523)}} {{=round(-W*radius)}} {{=round(W*radius)}} {{=round(-W*radius*0.5523)}} {{=round(W*radius)}} 0{\\p0}"] },
  { name: "highlight_box", kind: "text", timing: "range", tags: ["info", "highlight", "explain"],
    description: "A see-through coloured box over part of the screen (top-left x,y and size w,h, all 0 to 1): mark a region.",
    params: { x: num(0, 0.95, 0.1), y: num(0, 0.95, 0.4), w: num(0.05, 1, 0.8), h: num(0.03, 1, 0.12), color: color("#FFD60A"), opacity: num(0.1, 0.8, 0.3) },
    ass: ["Dialogue: 4,{{from:time}},{{to:time}},Shape,,0,0,0,,{\\an7\\pos({{=round(W*x)}},{{=round(H*y)}})\\1c{{color:acolor}}\\1a{{opacity:alpha}}\\bord0\\shad0\\fad(100,100)\\p1}m 0 0 l {{=round(W*w)}} 0 l {{=round(W*w)}} {{=round(H*h)}} l 0 {{=round(H*h)}}{\\p0}"] },
];

// ── transitions (between two parts) ────────────────────────────────────
// Without a duration, a transition lasts the outline's "Transition length".

const XFADES: Record<string, string> = {
  fade: "a plain crossfade", dissolve: "a speckled dissolve", fadeblack: "through black", fadewhite: "through white", fadegrays: "through grey",
  fadefast: "a quick crossfade", fadeslow: "a slow crossfade", pixelize: "pixelates across (digital, glitchy)", radial: "a clock-hand sweep",
  circleopen: "an iris opening", circleclose: "an iris closing", circlecrop: "a circle crop", rectcrop: "a box crop", distance: "a distance-field morph",
  wipeleft: "wipe left", wiperight: "wipe right", wipeup: "wipe up", wipedown: "wipe down", wipetl: "wipe to top-left", wipetr: "wipe to top-right", wipebl: "wipe to bottom-left", wipebr: "wipe to bottom-right",
  slideleft: "slide left", slideright: "slide right", slideup: "slide up", slidedown: "slide down",
  smoothleft: "smooth slide left", smoothright: "smooth slide right", smoothup: "smooth slide up", smoothdown: "smooth slide down",
  coverleft: "the next shot covers from the right", coverright: "covers from the left", coverup: "covers from below", coverdown: "covers from above",
  revealleft: "the shot slides away left", revealright: "slides away right", revealup: "slides away up", revealdown: "slides away down",
  vertopen: "opens from a vertical line", vertclose: "closes to a vertical line", horzopen: "opens from a horizontal line", horzclose: "closes to a horizontal line",
  diagtl: "diagonal to top-left", diagtr: "diagonal to top-right", diagbl: "diagonal to bottom-left", diagbr: "diagonal to bottom-right",
  hlslice: "horizontal slices left", hrslice: "horizontal slices right", vuslice: "vertical slices up", vdslice: "vertical slices down",
  hblur: "a horizontal blur smear", squeezeh: "squeezes horizontally", squeezev: "squeezes vertically", zoomin: "zooms into the next shot",
  hlwind: "wind streaks left", hrwind: "wind streaks right", vuwind: "wind streaks up", vdwind: "wind streaks down",
};
const TRANSITIONS: EffectDef[] = [
  // The names outlines use.
  { name: "cut", kind: "transition", timing: "instant", tags: ["transition"], description: "a hard cut: the story continues directly" },
  { name: "crossfade", kind: "transition", timing: "instant", xfade: "fade", tags: ["transition", "soft"], description: "a crossfade: between two related moments, softly" },
  { name: "dip_black", kind: "transition", timing: "instant", xfade: "fadeblack", tags: ["transition", "sad", "ending"], description: "dip to black: before the final beat, or a big change of mood" },
  { name: "blur", kind: "transition", timing: "instant", xfade: "fade", around: [{ fx: "blur_dip" }], tags: ["transition", "time", "memory"], description: "blurs out of one moment and into the next: time passing, drifting into or out of a memory" },
  { name: "flash", kind: "transition", timing: "instant", xfade: "fadewhite", tags: ["transition", "reveal"], description: "through white: the biggest laugh or reveal, once per clip at most" },
  { name: "whip", kind: "transition", timing: "instant", xfade: "hblur", tags: ["transition", "fast", "comedy"], description: "a whip pan: a fast, funny jump" },
  { name: "slide", kind: "transition", timing: "instant", xfade: "slideleft", tags: ["transition", "playful"], description: "slides to the next point: playful" },
  { name: "zoom", kind: "transition", timing: "instant", xfade: "zoomin", tags: ["transition", "energy"], description: "zooms into the next moment: energetic" },
  { name: "iris", kind: "transition", timing: "instant", xfade: "circleopen", tags: ["transition", "opening"], description: "an iris opening: into the first moment after a cold open" },
  // Editors' transitions with their own timing.
  { name: "flash_cut", kind: "transition", timing: "instant", duration: 0.16, xfade: "fadewhite", tags: ["transition", "impact", "hype"], description: "a split-second white flash cut: hits, beats, hype" },
  { name: "impact_cut", kind: "transition", timing: "instant", duration: 0.35, around: [{ fx: "flash", params: { opacity: 0.8 } }, { fx: "zoom_punch", params: { amount: 0.14 } }], tags: ["transition", "impact", "anime", "hype"], description: "a hard cut hit with a flash and a zoom punch: anime and hype edits, on a beat" },
  { name: "glitch_cut", kind: "transition", timing: "instant", duration: 0.3, xfade: "pixelize", around: [{ fx: "glitch" }], tags: ["transition", "glitch", "tech"], description: "a digital glitch between shots" },
  { name: "whip_blur", kind: "transition", timing: "instant", duration: 0.3, xfade: "hblur", around: [{ fx: "motion_blur" }], tags: ["transition", "fast", "action"], description: "a whip pan with motion blur: fast action" },
  { name: "asset_wipe", kind: "transition", timing: "instant", duration: 0.8, special: "asset_transition", tags: ["transition", "gif", "custom"],
    description: "Plays one of your overlay files (a GIF, or a WebM/MOV with alpha, from assets/overlays) over the join; the cut happens halfway, hidden under it.",
    params: { file: { type: "asset", kinds: ["overlay"] }, key: oneOf(["none", "green", "black", "white"], "none", "a background colour to key out") } },
  ...Object.entries(XFADES).map(([name, d]): EffectDef => ({ name, kind: "transition", timing: "instant", xfade: name, tags: ["transition", "xfade"], description: d })),
];

// ── the clip's own audio, over a range ─────────────────────────────────

const VOICE: EffectDef[] = [
  { name: "reverb", kind: "voice", timing: "range", tags: ["emotional", "sad", "epic", "memory", "ending"],
    description: "Room reverb on the voice: a line that should hang in the air, memories, epic or sad endings.",
    params: { delay: num(20, 200, 60, "ms"), decay: num(0.1, 0.7, 0.35) },
    filter: "aecho=0.8:0.85:{{=round(delay)}}|{{=round(delay*1.7)}}|{{=round(delay*2.6)}}:{{decay}}|{{=decay*0.7}}|{{=decay*0.45}}" },
  { name: "echo", kind: "voice", timing: "range", tags: ["dramatic", "memory", "comedy"],
    description: "A distinct echo: dramatic last words, a memory repeating, comic emphasis.",
    params: { delay: num(100, 800, 320, "ms"), decay: num(0.2, 0.8, 0.45) },
    filter: "aecho=0.8:0.9:{{=round(delay)}}:{{decay}}" },
  { name: "muffled", kind: "voice", timing: "range", tags: ["sad", "memory", "dream", "underwater"],
    description: "Muffled, far-away sound: sad cuts, memories, dazed or underwater moments.",
    params: { cutoff: num(300, 3000, 700, "Hz") },
    filter: "lowpass=f={{=round(cutoff)}},lowpass=f={{=round(cutoff)}}" },
  { name: "telephone", kind: "voice", timing: "range", tags: ["comedy", "retro", "flashback", "radio"],
    description: "A thin phone or radio voice: phone calls, flashbacks, a narrator aside.",
    filter: "highpass=f=320,lowpass=f=3200,acrusher=bits=10:mix=0.3,volume=1.4" },
  { name: "pitch", kind: "voice", timing: "range", tags: ["comedy", "chipmunk", "deep", "villain"],
    description: "Changes the voice pitch without changing speed: 1.4 = chipmunk, 0.7 = deep villain voice.",
    params: { ratio: num(0.5, 2, 1.3) },
    filter: "rubberband=pitch={{ratio}}" },
  { name: "bass_boost", kind: "voice", timing: "range", tags: ["hype", "impact", "meme"],
    description: "Boosted bass: hype moments, meme-style emphasis.",
    params: { gain: num(3, 20, 10, "dB") },
    filter: "bass=g={{gain}}:f=110,alimiter=limit=0.9" },
  { name: "tremolo", kind: "voice", timing: "range", tags: ["dizzy", "trippy", "comedy"],
    description: "Wobbling volume: dizziness, trippy or comic moments.",
    params: { rate: num(2, 20, 8, "Hz"), depth: num(0.1, 1, 0.6) },
    filter: "tremolo=f={{rate}}:d={{depth}}" },
  { name: "robot", kind: "voice", timing: "range", tags: ["comedy", "tech", "robot"],
    description: "A flat robotic voice: tech jokes, AI, mocking.",
    filter: "afftfilt=real='hypot(re,im)*sin(0)':imag='hypot(re,im)*cos(0)':win_size=512:overlap=0.75" },
  { name: "bitcrush", kind: "voice", timing: "range", tags: ["glitch", "retro", "game"],
    description: "Crunchy low-bit sound: glitches, retro game moments.",
    params: { bits: num(2, 12, 6) },
    filter: "acrusher=bits={{=round(bits)}}:mix=0.7" },
  { name: "mute", kind: "voice", timing: "range", tags: ["silence", "dramatic", "comedy"],
    description: "Silences the clip's own audio: a dramatic silence, or to let a sound effect or music take over.",
    filter: "volume=0" },
  { name: "volume", kind: "voice", timing: "range", tags: ["mix"],
    description: "Makes the clip's own audio louder or quieter over the range.",
    params: { gain: num(0, 3, 0.5) },
    filter: "volume={{gain}}" },
  { name: "reverse_audio", kind: "voice", timing: "range", tags: ["weird", "horror", "rewind"],
    description: "Plays the audio backwards over the range: rewinds, spooky or surreal moments.",
    filter: "areverse" },
];

// ── your files ─────────────────────────────────────────────────────────

const FILES: EffectDef[] = [
  { name: "overlay", kind: "asset", timing: "range", special: "asset", tags: ["gif", "sticker", "overlay", "custom"],
    description: "Lays one of your files (GIF, WebM/MOV with alpha, PNG from assets/overlays or assets/images) over the clip: stickers, reactions, fire, sparkles, frames.",
    params: {
      file: { type: "asset", kinds: ["overlay", "image"] },
      position: oneOf(["full", "center", "top", "bottom", "left", "right", "top_left", "top_right", "bottom_left", "bottom_right"], "center"),
      scale: num(0.1, 1, 0.5, "width as a share of the frame (full ignores it)"),
      key: oneOf(["none", "green", "black", "white"], "none", "a background colour to key out"),
      opacity: num(0.1, 1, 1),
    } },
  { name: "ambience", kind: "sound", timing: "range", special: "sfx_bed", tags: ["ambience", "bed", "nostalgia", "silence"],
    description: "Loops a recorded sound quietly under a range: crickets for an awkward pause, clock_ticking for suspense, typing under typed text. Keep it low and short, and keep noise (hiss, crackle) out from under speech: on a phone it sounds like static.",
    params: { file: { type: "asset", kinds: ["sfx"] }, gain: num(0, 1.2, 0.3, "loudness next to the voice"), fade: num(0, 3, 0.6, "fade in and out (s)") } },
  { name: "sfx", kind: "sound", timing: "instant", special: "sfx_file", tags: ["custom", "sound"],
    description: "Plays a recorded sound once: one from the built-in sound library or your assets/sfx (file = its name).",
    params: { file: { type: "asset", kinds: ["sfx"] }, gain: gain(0.8) } },
  { name: "music", kind: "music", timing: "range", special: "music", tags: ["music", "mood", "custom"],
    description: "A music bed from assets/music under the range (the whole clip by default), ducked under speech.",
    params: {
      file: { type: "asset", kinds: ["music"] },
      volume: num(0.05, 1, 0.25), duck: num(0, 1, 0.7, "how much it dips under speech"),
      offset: num(0, 600, 0, "start this many seconds into the song"), fade: num(0, 5, 1.5, "fade in and out (s)"),
    } },
];

export const BUILTIN: EffectDef[] = [...SEGMENT, ...VIDEO, ...GRAPHIC, ...TEXT, ...TRANSITIONS, ...VOICE, ...FILES].map((e) => ({ ...e, origin: "builtin" as const }));
