// Build everything into dist/: the Director (Think worker) bundle, the UI, and the Bun server.
import { rmSync } from "node:fs";
import { join } from "node:path";

const APP = join(import.meta.dir, "..");
const step = (name: string) => console.log(`\n▸ ${name}`);
rmSync(join(APP, "dist"), { recursive: true, force: true });

step("worker (wrangler bundle)");
// Wrangler's bundler runs fine on Bun (same output as on Node), so a checkout needs only Bun.
const wr = Bun.spawnSync(
  [process.execPath, "node_modules/wrangler/bin/wrangler.js", "deploy", "--dry-run", "--outdir", "dist/worker"],
  { cwd: APP, stdout: "inherit", stderr: "inherit", env: { ...process.env, WRANGLER_SEND_METRICS: "false" } },
);
if (wr.exitCode !== 0) process.exit(wr.exitCode ?? 1);

step("ui");
const ui = await Bun.build({
  entrypoints: [join(APP, "src/ui/index.html")],
  outdir: join(APP, "dist/ui"),
  minify: true,
  sourcemap: "linked",
  define: { "process.env.NODE_ENV": '"production"' },
});
if (!ui.success) {
  for (const l of ui.logs) console.error(l);
  process.exit(1);
}
ui.outputs.forEach((o) => console.log(`  ${o.path.replace(APP, ".")}  ${(o.size / 1024).toFixed(0)} KB`));

step("server");
const srv = await Bun.build({
  entrypoints: [join(APP, "src/server/main.ts")],
  outdir: join(APP, "dist/server"),
  target: "bun",
  minify: true,
});
if (!srv.success) {
  for (const l of srv.logs) console.error(l);
  process.exit(1);
}
// The desktop shell needs to know where this app folder lives (dist/, node_modules/wrangler).
await Bun.write(
  join(APP, "src/desktop/home.gen.ts"),
  `// Generated by scripts/build.ts. Override at runtime with MRCLIPPER_HOME.\nexport const APP_HOME = ${JSON.stringify(APP.replaceAll("\\", "/"))};\n`,
);

console.log("\nBuilt. Start with: bun start  (browser)  or  bun run desktop  (desktop app)");
